on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
          always-auth: true
      - name: Install
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Test
        run: pnpm test
